"""my second migrate file

Revision ID: 7c1a64c0e9f2
Revises: 
Create Date: 2023-05-22 12:59:47.219577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1a64c0e9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_db', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
